### ISSUE TITLE
func name should be install_* instead of has_*

### ISSUE THREAD

**Issue by kkweon** [mrchypark/multilinguer#11]
https://github.com/mrchypark/multilinguer/blob/3478a8f13b60ea2f1fd459676be81d145b678645/R/has.R

**Comment by mrchypark** [comment]
Thank you for your good suggestion. 

I will consider it. 

I understand what your saying. I know about this issue.
I want to has_* func name looks like declarative status.

Anyway, multilinguer package import correttor and conda4r packages for java & python.
There packages have func install_corretto and install_conda.

**Comment by kkweon** [comment]
Sorry, I don't understand. 

`has_*` name implies it's a pure function that simply returns boolean, but it has a pretty big side effect, which is not expected based on the function name.

But, that's just my 2 cents. closing.

**Comment by mrchypark** [comment]
Oh, I understand.

Do you have any suggestion? I don't want to use `install_*` name.

**Comment by kkweon** [comment]
![image](https://user-images.githubusercontent.com/2981167/63175548-13b67f80-bff9-11e9-9432-3b6daa61fa07.png)

**Comment by mrchypark** [comment]
I change has_* to install_*. 

thank you for issue!

**Comment by mrchypark** [comment]
그러게요. 이제와서 보니 has라고 하면 check 동작이어야 이해하기 쉽군요.
