### ISSUE TITLE
KoNLP 설치 관련 - multilinguer 설치 관련

### ISSUE THREAD

**Issue by Kwookpark** [mrchypark/multilinguer#16]
안녕하세요, 

KoNLP 설치 관련 아래 페이스북에 가이드 작성/공유해 주신것 감사히 보고 있습니다. 
https://www.facebook.com/notes/r-korea-krugkorean-r-user-group/konlp-%EC%84%A4%EC%B9%98-%EC%9D%B4%EC%8A%88-%EA%B3%B5%EC%9C%A0/1847510068715020/

공유주신 내용 중, 

java, rJava 설치 install.packages("multilinguer")
library(multilinguer)
install_jdk()

부분에서, 다음과 같이 에러가 발생하면서 multilinguer 설치가 되지 않네요.  
(Windows  사용자입니다.)

> install.packages("multilinguer")
Installing package into ‘C:/Users/USER/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘multilinguer’ is not available (for R version 3.5.3)

혹시, 어떻게 대처하면 좋을지 아무쪼록 부탁드립니다. 

미리 감사드립니다. (_ _)

**Comment by mrchypark** [comment]
안녕하세요,
아마 지금 R 버전이 3.6 대 인걸로 알고 있는데요.제가 이 패키지를 올릴때 3.5 이후에 작업해서 cran에서 사용하실 때는 3.6 버전 이상만 가능할 것 같습니다.
혹시 remote로 설치해보시겠어요?

```
remotes::install_gitlab("mrchypark/multilinguer")
```

**Comment by Kwookpark** [comment]
앗 감사합니다! 
말씀주신 대로 진행하니, 덕분에 무사히 설치완료했습니다! 
좋은 하루 되세요 :)
