### ISSUE TITLE
에러가 발생하였습니다.

### ISSUE THREAD

**Issue by Hyeji-Jo** [mrchypark/multilinguer#17]
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949    LC_MONETARY=Korean_Korea.949
[4] LC_NUMERIC=C                 LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] multilinguer_0.0.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       binman_0.1.1     fansi_0.4.1      crayon_1.3.4     assertthat_0.2.1
 [6] R6_2.4.1         sys_3.3          semver_0.2.0     magrittr_1.5     zip_2.0.4       
[11] httr_1.4.1       cli_2.0.2        rlang_0.4.5      remotes_2.1.1    rstudioapi_0.11 
[16] fs_1.4.1         xml2_1.3.1       tools_3.6.3      wdman_0.2.5      glue_1.4.0      
[21] compiler_3.6.3   askpass_1.1      rvest_0.3.5      usethis_1.6.0   

> install.packages("Java")
Installing package into ‘C:/Users/johj4/OneDrive/문서/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Java’ is not available (for R version 3.6.3)
> install.packages("multilinguer")
Installing package into ‘C:/Users/johj4/OneDrive/문서/R/win-library/3.6’
(as ‘lib’ is unspecified)
URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/multilinguer_0.0.4.zip'을 시도합니다
Content type 'application/zip' length 46140 bytes (45 KB)
downloaded 45 KB

package ‘multilinguer’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\johj4\AppData\Local\Temp\RtmpEJgFyw\downloaded_packages
> # install.packages("multilinguer")
> library(multilinguer)
If you have any problem, please issue here.
https://github.com/mrchypark/multilinguer/issues
> install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 184907881 bytes (176.3 MB)
downloaded 176.3 MB

경고: 저장하는 데이터를 1024문자로 잘라냅니다.
√ Adding 'JAVA_HOME=C:/Users/johj4/corretto/jdk11.0.7_10' to 'C:/Users/johj4/OneDrive/??/.Renviron'
Error in file(path, open = file_mode, encoding = "utf-8") : 
  커넥션을 열 수 없습니다
추가정보: 경고메시지(들): 
In file(path, open = file_mode, encoding = "utf-8") :
  파일 'C:/Users/johj4/OneDrive/??/.Renviron'를 여는데 실패했습니다: Invalid argument

**Comment by mrchypark** [comment]
안녕하세요, 사용자 폴더가 원드라이브 인데다, 폴더 경로중에 한글이 포함되어있네요.

이 부분은 고민을 좀 해보겠습니다.
문서 폴더가 원드라이브로 되어 계신 분이 꽤 계신데, 제가 원드라이브를 안쓰니 상황 파악이 쉽지 않았네요.

이렇게 이슈 등록해주셔서 대단히 감사합니다 . :)

**Comment by mrchypark** [comment]
.Renviron 파일에 설치하는 동작을 제거하였습니다.

아마 정상동작하리라 기대합니다.

remotes::install_gitlab("mrchypark/multilinguer")

위 개발버전으로 설치해봐주세요 감사합니다.
