### ISSUE TITLE
tabulizer 때문에 Java를 설치해야 하는데... 버전이 맞지 않아...

### ISSUE THREAD

**Issue by statkclee** [mrchypark/multilinguer#18]
tabulizer 때문에 Java를 설치해야 하는데... 버전이 맞지 않아...오류가 발생된 것을 확인했습니다.
`corretto/jdk11.0.7_10` 버전대신 이전 openjdk로 설치를 해야 되서... 혹시 설치된 자바를 삭제 제거하는 기능도 있을까요?

**Comment by mrchypark** [comment]
안녕하세요 경로는 `fs::path(fs::path_home(), "corretto")` 에 있습니다.

multilinguer가 설치하는 자바는 이 폴더를 제거하고, 환경변수를 확인하시면 됩니다.
multilinguer가 설치한 자바를 제거하는 기능이 필요하겠네요.
기존 설치 자바를 제거하는 것은 이 패키지의 범위를 벗어난다고 생각합니다.

이슈 등록해주셔서 감사합니다.
