### ISSUE TITLE
이 문제 해결해주세요~~

### ISSUE THREAD

**Issue by KIMTAEGEON** [mrchypark/multilinguer#19]
> install.packages("multilinguer")
URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/multilinguer_0.0.4.zip'을 시도합니다
Content type 'application/zip' length 45744 bytes (44 KB)
downloaded 44 KB

package ‘multilinguer’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\김호건\AppData\Local\Temp\Rtmp4qbKkt\downloaded_packages
> library(multilinguer)
If you have any problem, please issue here.
https://github.com/mrchypark/multilinguer/issues
> install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 184907881 bytes (176.3 MB)
downloaded 176.3 MB

Error in dir.create(x, showWarnings = FALSE, recursive = TRUE, ...) : 
  파일명 전환에 문제가 있습니다 -- 이름이 너무 긴가요?

이러한 에러가 발생하는데 어떻게 해결해야 하나요??

**Comment by mrchypark** [comment]
https://github.com/mrchypark/multilinguer/issues/17 이 이슈랑 같은 문제 입니다.

경로에 한글이 있네요.

이 이슈는 닫고 위 이슈 번호에서 해결하도록 하겠습니다.
이슈잉 해주셔서 대단히 감사합니다. :)
