### ISSUE TITLE
코로나 단어추출

### ISSUE THREAD

**Issue by KIMTAEGEON** [mrchypark/multilinguer#21]
R 에서 코로나 단어를 사전추가 하였으나,,,,
extranoun함수를 사용하여 추출하면 "코" "나" 이렇게 자꾸 검색이됩니다.
혹시 무엇이 문제일까요??

**Comment by mrchypark** [comment]
안녕하세요 extranoun 함수는 KoNLP 패키지에 있는 함수이니 https://github.com/haven-jeon/KoNLP 이곳에 이슈 등록해주시면 감사하겠습니다.

그리고 형태소 분석기는 확율기반으로 동작하기 때문에, 사전에 추가하였다고 하여도 100% 우선순위를 가지고 추출하지않는 것으로 알고 있습니다. 감사합니다.
