### ISSUE TITLE
install_jdk() 중 오류

### ISSUE THREAD

**Issue by han-garam-alpha** [mrchypark/multilinguer#23]
R 4.0.1 사용중입니다. rtools35 설치 후 텍스트 마이닝을 하려고 패키지를 설치하던 중 install_jdk()에서 오류가 발생합니다

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
install.packages("multilinguer")
--- 현재 세션에서 사용할 CRAN 미러를 선택해 주세요 ---
URL 'https://cran.biodisk.org/bin/windows/contrib/4.0/multilinguer_0.0.4.zip'을 시도합니다
Content type 'application/zip' length 45886 bytes (44 KB)
downloaded 44 KB

패키지 ‘multilinguer’를 성공적으로 압축해제하였고 MD5 sums 이 확인되었습니다

다운로드된 바이너리 패키지들은 다음의 위치에 있습니다
        C:\Users\조하람\AppData\Local\Temp\RtmpCWKAFV\downloaded_packages
> library(multilinguer)
If you have any problem, please issue here.
https://github.com/mrchypark/multilinguer/issues
경고메시지(들): 
패키지 ‘multilinguer’는 R 버전 4.0.2에서 작성되었습니다 
> install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 184907881 bytes (176.3 MB)
downloaded 176.3 MB

Error in dir.create(x, showWarnings = FALSE, recursive = TRUE, ...) : 
  파일명 전환에 문제가 있습니다 -- 이름이 너무 긴가요?
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
어떻게 해결할 수 있을까요?

**Comment by mrchypark** [comment]
안녕하세요 폴더 이름이 문제가 안되려고 노력했는데, 관련 문제인거 같네요.
현재 fs 라는 패키지의 함수들에 의존해서 경로를 만드는데요.

 fs::path(fs::path_home(), "corretto")

이 함수를 실행하고 에러가 나는지 알려주시면 좋을 것 같아요.

자바 설치 파일 다운로드 경로는 아래 함수입니다.

fs::path(fs::path_temp(), "crt.zip")

**Comment by han-garam-alpha** [comment]
> fs::path(fs::path_temp(), "crt.zip")
C:/Users/조하람/AppData/Local/Temp/Rtmp2zrrUa/crt.zip
> fs::path(fs::path_home(), "corretto")
Error in base::nchar(x, type, allowNA, keepNA) : 
  invalid multibyte string, element 1

이런 오류 메시지가 뜹니다

**Comment by mrchypark** [comment]
path_home 에서 문제가 발생하는군요. 공유해주셔서 감사합니다.

관련해서 내용 수정해보도록하겠습니다.

**Comment by mrchypark** [comment]
@han-garam-alpha 님 문제를 해결하려면 수동으로 해야 하는데, 제가 그 대비를 잘 안해놨네요 ㅠ

함수 동작을 좀 정리해보겠습니다.

**Comment by leo00269** [comment]
안녕하세요 R공부중에 KoNLP 패키지 관련 설치 중 문제가 있어서 문의드립니다.
install_jdk()에서 오류가 발생해서 질문드립니다.
이렇게 error가 나와서 인코딩 문제인가요??
Error in file(path, open = file_mode, encoding = "utf-8"): 커넥션을 열 수 없습니다
Traceback:

1. install_jdk()
2. set_java_home(os)
3. set_java_home.Windowsx64(os)
4. usethis::write_union(fs::path(fs::path_home_r(), "/", ext = "Renviron"), 
 .     forenvron)
5. write_utf8(path, all)
6. file(path, open = file_mode, encoding = "utf-8")

**Comment by kim7871** [comment]
저도 동일한 문제가 발생합니다. Username이 한글로 설정되어있어서 그런 것 같은데 혹시 이슈를 해결하셨나요 ㅠㅠ
수동으로 처리하는 방법이라도 알고있으면 시도해보겠는데 참 곤란하네요...
이하는 오류메세지입니다.

다운로드된 바이너리 패키지들은 다음의 위치에 있습니다
        C:\Users\김신우\AppData\Local\Temp\Rtmp46VhfV\downloaded_packages
> install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 185607712 bytes (177.0 MB)
downloaded 177.0 MB

Error in dir.create(x, showWarnings = FALSE, recursive = TRUE, ...) : 
  파일명 전환에 문제가 있습니다 -- 이름이 너무 긴가요?
> warnings()
경고 메시지:

> fs::path(fs::path_home(), "corretto")
Error in base::nchar(x, type, allowNA, keepNA) : 
  invalid multibyte string, element 1

**Comment by mrchypark** [comment]
사용자 이름이 한글인 경우 문제가 있습니다.

이 부분을 관리자 권한이 필요해서 어떻게 우회할 수 없나 고민하고 있습니다.
빨리 문제를 해결해보도록 하겠습니다.

문제 공유해주셔서 대단히 감사합니다.

**Comment by Kimgh1** [comment]
> install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 186585821 bytes (177.9 MB)
downloaded 177.9 MB

에러: package ‘fansi’ does not have a namespace

**Comment by mrchypark** [comment]
경로가 한글인 경우 c://multilinguer 폴더를 새로 만들어서 설치하도록 수정하였습니다.

https://cran.r-project.org/web/packages/multilinguer/index.html
