### ISSUE TITLE
> install_jdk() 시 에러발생했습니다.

### ISSUE THREAD

**Issue by BYUNGKWON-JUNG** [mrchypark/multilinguer#24]
> install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 185607712 bytes (177.0 MB)
downloaded 177.0 MB

√ Adding 'JAVA_HOME=C:/Users/bkjung/corretto/jdk11.0.8_10' to 'C:/Users/bkjung/OneDrive/??/.Renviron'
Error in file(path, open = file_mode, encoding = "utf-8") : 
  커넥션을 열 수 없습니다
추가정보: 경고메시지(들): 
In file(path, open = file_mode, encoding = "utf-8") :
  파일 'C:/Users/bkjung/OneDrive/??/.Renviron'를 여는데 실패했습니다: Invalid argument

**Comment by mrchypark** [comment]
이 동작은 rstudio를 재시작 하지 않아도 사용할 수 있도록 하는 편의 기능인데요.

제거 함으로써 문제를 해결 할 수 있을 것 같습니다.

혹시 github 버전으로 패키지 설치해서 시도해봐주실 수 있으신가요?
제가 onedrive가 없어서 테스트 하기가 어렵네요 ㅠ

**Comment by mrchypark** [comment]
아래 코드로 설치하신 이후에 진행해보시면 됩니다.

```
install.packages("remotes")
remotes::install_github("mrchypark/multilinguer")
```
