### ISSUE TITLE
install_jdk() error

### ISSUE THREAD

**Issue by dugtuna** [mrchypark/multilinguer#25]
> install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 185607712 bytes (177.0 MB)
downloaded 177.0 MB

Error in zip::unzip(...) : 
  zip error: `Cannot extract file `jdk11.0.8_10/bin/server/jvm.dll`` in file `zip.c:211`

**Comment by mrchypark** [comment]
으잉? 압축 해제가 안되는군요? 살펴보겠습니다. 이슈 공유해주셔서 감사합니다.

혹시 sessionInfo() 도 공유해주실 수 있으실까요?

**Comment by dugtuna** [comment]
> install.packages("https://cran.r-project.org/src/contrib/Archive/KoNLP/KoNLP_0.0-7.4.tar.gz", repos = NULL, type="source")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
URL 'https://cran.r-project.org/src/contrib/Archive/KoNLP/KoNLP_0.0-7.4.tar.gz'을 시도합니다
Content type 'application/x-gzip' length 4554118 bytes (4.3 MB)
downloaded 4.3 MB

* installing *source* package 'KoNLP' ...
** 패키지 'KoNLP'는 성공적으로 압축해제되었고, MD5 sums 이 확인되었습니다
** R
** inst
** byte-compile and prepare package for lazy loading
경고: package 'rJava' was built under R version 3.5.3
** help
*** installing help indices
  converting help for package 'KoNLP'
    finding HTML links ... 완료
    DicConfPath                             html  
    KoNLP                                   html  
    MorphAnalyzer                           html  
    SimplePos09                             html  
    SimplePos22                             html  
    convertHangulStringToJamos              html  
    convertHangulStringToKeyStrokes         html  
    doKoMorph                               html  
    extractNoun                             html  
    is.hangul                               html  
    makeTagList                             html  
    pkgKoNLP                                html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
경고: package 'rJava' was built under R version 3.5.3
Error: package or namespace load failed for 'rJava':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: 공유된 객체 'C:/Program Files/R/R-3.5.2/library/rJava/libs/i386/rJava.dll'를 로드 할 수 없습니다:
  LoadLibrary failure:  %1은(는) 올바른 Win32 응용 프로그램이 아닙니다.

Error : package 'rJava' could not be loaded
에러: 로딩에 실패했습니다
실행이 정지되었습니다
*** arch - x64
경고: package 'rJava' was built under R version 3.5.3
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.5.2/library/KoNLP'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/elrh3/AppData/Local/Temp/RtmpKYG3wx/downloaded_packages/KoNLP_0.0-7.4.tar.gz’ had non-zero exit status



> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949   
[3] LC_MONETARY=Korean_Korea.949 LC_NUMERIC=C                
[5] LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2   

현재 R 3.5.2 사용중입니다.

**Comment by Kimgh1** [comment]
Error in dir.create(x, showWarnings = FALSE, recursive = TRUE, ...) : 
  파일명 전환에 문제가 있습니다 -- 이름이 너무 긴가요?

install_jdk()단계에서 위의 오류가 뜹니다.
C:/사용자/한글이름 이여서 그런걸까요??

**Comment by mrchypark** [comment]
@Kimgh1 안녕하세요, 그게 맞는거 같습니다.

이 문제는 제가 알고 있는 문제여서 고쳐보려고 하고 있습니다.
이슈 댓글로 알려주셔서 정말 감사드립니다.

**Comment by Kimgh1** [comment]
답변 감사합니다.  결국 윈도우포맷으로 한글이름 변경했어요. ㅠㅠ

문의드렸던
> library(KoNLP)
에러: package or namespace load failed for ‘KoNLP’:
 패키지 ‘fansi’는 네임스페이스를 가지고 있지 않습니다

내용은 install.packages("fansi")로 해결했어요. 이리 간단한 것을 여쭤봐서...민망합니다. 
건강하시고 좋은 날 보내세요.

**Comment by daeunni** [comment]
안녕하세요, 저도 비슷한 에러를 경험해서 문의 드립니다. 

R version은 4.1.2이고, 윗 분과 비슷한 error를 경험했는데 path에 한글 이름이 따로 들어가진 않아서요. 
error는 다음과 같습니다. 

```
Error: package or namespace load failed for ‘rJava’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/mokji/OneDrive/Documents/R/win-library/4.1/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  %1은(는) 올바른 Win32 응용 프로그램이 아닙니다.
```

해결 방안을 알 수 있을까요? 
감사합니다.
