### ISSUE TITLE
Windows10 R version 4.0.2 (2020-06-22) RStudio Version 1.3.1073에서 install_jdk() error

### ISSUE THREAD

**Issue by SH-Baik** [mrchypark/multilinguer#26]
Windows10
R version 4.0.2 (2020-06-22)
RStudio Version 1.3.1073
에서 다음과 같은 에러가 뜹니다. jdk도 새로 설치해봤는데도 계속 같은 에러 메시지가 뜨는데 이유를 모르겠습니다.

install_jdk()
URL 'https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip'을 시도합니다
Content type 'application/zip' length 185607712 bytes (177.0 MB)
downloaded 177.0 MB

Error in zip::unzip(...) :
zip error: Cannot extract file jdk11.0.8_10/bin/java.dll`` in file zip.c:211

**Comment by mrchypark** [comment]
install.packages("remotes")
remotes::install_github("mrchypark/multilinguer")

현재 개발버전에서 해결된 것으로 예상됩니다.
위 코드로 개발버전을 설치하고 실행해봐 주세요. 감사합니다.
