### ISSUE TITLE
library(multilinguer)에서 오류 발생했습니다.

### ISSUE THREAD

**Issue by eopr12** [mrchypark/multilinguer#28]
KoNLP도 ㅇㅇㅇ에서 작성되었습니다라는 오류 때문에 이걸 진행하는건데
여기서도 비슷한 오류가 발생하네요.

오류메세지:
The downloaded source packages are in
	‘C:\Users\Becky\AppData\Local\Temp\RtmpkvL4BS\downloaded_packages’
> library(multilinguer)
If you have any problem, please issue here.
https://github.com/mrchypark/multilinguer/issues
경고메시지(들): 
패키지 ‘multilinguer’는 R 버전 3.5.3에서 작성되었습니다

**Comment by mrchypark** [comment]
R 버전 3.5.3에서 작성되었습니다 <- 이 메세지는 오류가 아니고 버전이 다른 것에 대한 경고입니다.
아마 실행시 정상 동작할 것으로 예상합니다.
감사합니다.
