### ISSUE TITLE
KoNLP 설치가 제대로 안 된 것 같습니다.

### ISSUE THREAD

**Issue by ljaegeon** [mrchypark/multilinguer#30]
KoNLP 패키지를 페이스북 페이지에 안내 된대로 설치를 진행 했는데 설치 과정에 에러 메시지는 없었거든요.
경고메시지는 몇번 뜨기는 했는데..
useNIADic() 이걸 실행하면 밑에 이미지 보시는 것처럼 나오는데 이럴 땐 어떻게 해야 되는 건가요.

![워닝](https://user-images.githubusercontent.com/74650979/99509982-d85beb00-29c9-11eb-8e35-ab6a5ca4ae9e.png)

그리고 extractNoun 이 함수를 입력하면 "함수 "extractNoun"를 찾을 수 없습니다."라는 에러 메시지가 뜨는데
KoNLP 패키지 설치가 제대로 안 돼서 그런거죠?
뭘 뺴먹은 것 같은데 뭔지 모르겠습니다.

**Comment by mrchypark** [comment]
안녕하세요, 위에 질문은 현재 설치되어 있는 패키지들 중에 함께 업데이트가 가능한 리스트를 보여주면서 지금 같이 업데이트 할껀지를 묻는 내용입니다. 전체 설치는 1번을, cran 패키지만 설치는 2번을, 지금 설치하지 않을꺼면 3번을, 개별로 지정하고 싶으면 각각의 번호를 입력하시면 됩니다.

저는 보통 1번 합니다만, 함께 업데이트하다가 문제가 생기는 경우가 종종 있어서 다른 분들에게는 3번을 권해드리고 있습니다.

"함수 "extractNoun"를 찾을 수 없습니다." <- 라고 나오는 경우는 library("KoNLP")를 안하셔서 그랬을꺼라 짐작합니다만,
`KoNLP::extractNoun("어떤 글자")` 라고 하셨을 때 동작하지 않는다면 설치가 제대로 안 된 것이 맞습니다.

별건이긴 합니다만, 형태소 분석기 쓰시려고 하시는거면 https://github.com/mrchypark/Elbird/blob/main/README_kr.md 이것도 한번 살펴봐주세요.

감사합니다.

**Comment by ljaegeon** [comment]
답변 감사합니다.
참고로 말씀드리면 제가 지금 "DO IT 쉽게 배우는 R데이터 분석"이라는 책으로 공부하던 중이었습니다.
library("KoNLP") 이것도 다 했고 알려주신대로 "어떤글자" 했을때 제가 언급한"함수 "extractNoun"를 찾을 수 없습니다"라는
메시지가 뜨는데요.
그럼 처음부터 전부 다 다시 시도해 봐야 되는 건가요?

**Comment by mrchypark** [comment]
@ljaegeon library(KoNLP) 이렇게 했는데, 뭔가 다른 메세지가 나오거나 하나요?

**Comment by ljaegeon** [comment]
아~"Checking user defined dictionary!" 라고 나오네요.

**Comment by mrchypark** [comment]
음? 그럼 문제없이 동작하는건데 이상하네요. 이후에 KoNLP::extractNoun("어떤 글자") 이거 해보시겠어요?

**Comment by ljaegeon** [comment]
귀찮게 해드려서 죄송합니다.
전부 다 처음부터 다시 해서 KoNLP::extractNoun("어떤 글자") 이렇게 하니까.
"에러: 패키지 ‘vctrs’는 네임스페이스를 가지고 있지 않습니다" 이렇게 한글로 메시지가 뜹니다.

**Comment by mrchypark** [comment]
`install.packages("vctrs")` 이거 하시고 다시 해보시겠어요?

**Comment by ljaegeon** [comment]
이렇게 나오는데 맨밑에 나와 있는 경로로 들어가보니까 압축파일 형태로 파일이 하나 있긴 한데
설치가 잘 안 된거죠?
Installing package into ‘C:/Users/eback/OneDrive/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
      binary source needs_compilation
vctrs  0.3.4  0.3.5              TRUE

installing the source package ‘vctrs’

URL 'https://cran.rstudio.com/src/contrib/vctrs_0.3.5.tar.gz'을 시도합니다
Content type 'application/x-gzip' length 1055792 bytes (1.0 MB)
downloaded 1.0 MB

ERROR: failed to lock directory 'C:/Users/eback/OneDrive/Documents/R/win-library/4.0' for modifying
Try removing 'C:/Users/eback/OneDrive/Documents/R/win-library/4.0/00LOCK-vctrs'
Warning in install.packages :
  installation of package ‘vctrs’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\eback\AppData\Local\Temp\RtmpoTeuHJ\downloaded_packages’

**Comment by mrchypark** [comment]
Try removing 'C:/Users/eback/OneDrive/Documents/R/win-library/4.0/00LOCK-vctrs'

이 결로의 폴더를 제거하고 다시 설치해보시겠어요?
