### ISSUE TITLE
library(KoNLP) 오류 해결 방법 좀 부탁 드립니다. 

### ISSUE THREAD

**Issue by angelcjh95** [mrchypark/multilinguer#31]
> library(KoNLP)
Error in get(genname, envir = envir) : 
  객체 'testthat_print'를 찾을 수 없습니다
Checking user defined dictionary! 
이런 오류 문구가 뜹니다.. 무엇이 문제일까요? ㅠ.ㅠ.

**Comment by mrchypark** [comment]
@angelcjh95 안녕하세요! 알려주셔서 감사합니다. 최근 버전에서 뭔가 문제가 있는 것 같습니다. 이건 개별 패키지에서의 문제로 보이는데요. KoNLP 쪽에 문의하시는 것이 빠를 것 같긴 합니다.

대체적으로 많은 패키지에서 사용하는 testthat 패키지 관련 호환 문제로 보이니 저 또한 살펴보겠습니다. 감사합니다.
