### ISSUE TITLE
install_jdk()오류

### ISSUE THREAD

**Issue by Minseok-choi97** [mrchypark/multilinguer#32]
install 중 에러코드가 발생하여 문의 드립니다.
√ Adding 'JAVA_HOME=C:/Users/minse/corretto/jdk11.0.10_9' to 'C:/Users/minse/OneDrive/¹®¼­/.Renviron'
Error in file(path, open = file_mode, encoding = "utf-8") : 
  커넥션을 열 수 없습니다
추가정보: 경고메시지(들): 
In file(path, open = file_mode, encoding = "utf-8") :
  파일 'C:/Users/minse/OneDrive/¹®¼­/.Renviron'를 열 수 없습니다: No such file or directory
>

**Comment by mrchypark** [comment]
안녕하세요, 4.0.x 버전에서 인코딩 이슈가 있는 것을 파악했습니다.

우선 임시 폴더나 한글 경로일 경우 수정하는 안내사항을 작성하려고 합니다.

이렇게 @Minseok-choi97  이슈 알려주셔서 정말 감사드립니다.

**Comment by Minseok-choi97** [comment]
그렇다면 혹시 KoNLP패키지를 설치하는 다른 방법이 있을까요?

**Comment by mrchypark** [comment]
@Minseok-choi97 

패키지가 제공하는 기능은 jdk를 설치하고 경로 환경 변수를 지정해주는 것입니다.
이걸 수동으로 진행하시면 됩니다.

**Comment by mrchypark** [comment]
@all-contributors please add @Minseok-choi97 for bug
