### ISSUE TITLE
Issue # 25 와 같은 install_jdk() error 관련 문의드립니다. 

### ISSUE THREAD

**Issue by daeunni** [mrchypark/multilinguer#36]
안녕하세요, 저도 비슷한 에러를 경험해서 문의 드립니다. 

R version은 4.1.2이고, 윗 분과 비슷한 error를 경험했는데 path에 한글 이름이 따로 들어가진 않아서요. 
error는 다음과 같습니다. 

```
Error: package or namespace load failed for ‘rJava’:
 .onLoad가 loadNamespace()에서 'rJava'때문에 실패했습니다:
  호출: inDL(x, as.logical(local), as.logical(now), ...)
  에러: unable to load shared object 'C:/Users/mokji/OneDrive/Documents/R/win-library/4.1/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  %1은(는) 올바른 Win32 응용 프로그램이 아닙니다.
```

해결 방안을 알 수 있을까요? (issue 25가 closed 되어 새로 issue를 업로드합니다.)
감사합니다.

**Comment by mrchypark** [comment]
@daeunni 안녕하세요, 혹시 실행코드 전체와 메세지 전체를 볼 수 있을까요?
보여주신 메세지는 jdk가 설치되지 않아서 없을 때 rJava가 출력하는 에러입니다.

**Comment by daeunni** [comment]
넵 말씀하신대로 rJava 문제였고 환경변수 설정으로 해결했습니다. 감사드립니다! :)

**Comment by mrchypark** [comment]
감사합니다. :)

**Comment by mrchypark** [comment]
@all-contributors please add @daeunni for bug
