### ISSUE TITLE
jdk 패키지 설치 오류 관련해서 말씀드립니다

### ISSUE THREAD

**Issue by jamesleeeee** [mrchypark/multilinguer#37]
![image](https://user-images.githubusercontent.com/95525262/144704809-87be09cf-ad9a-43c8-9f88-8ef8b7da09f1.png)

]
계속해서 이런 오류가 발생합니다 ㅠㅠ

**Comment by mrchypark** [comment]
안녕하세요.

```
install.packages("remotes")
remotes::install_github("mrchypark/multilunguer")
```
로 개발버전을 설치하고 다시 진행해 보시겠어요?
그리고 혹시 괜찮으시면 메일로 연락주시면, 직접 컴퓨터 상태를 확인할 수 있으면 좋겠습니다.

감사합니다.

**Comment by jamesleeeee** [comment]
메일로 연락드렸습니다. 감사합니다.

**Comment by mrchypark** [comment]
@all-contributors please add @jamesleeeee for test bug
