### ISSUE TITLE
install_jdk() error 관련 문의드립니다.

### ISSUE THREAD

**Issue by Joyeoh** [mrchypark/multilinguer#38]
R 버전 4.1.2 버전 에서 remotes::install_gitlab("mrchypark/multilinguer") 통해 multilinger을 설치한후 
install_jdk()를 실행했을 때  zip error: `Cannot open zip file `/tmp/RtmpFMwYDt/crt.tar.gz` for reading` in file `zip.c:140` 오류가 떠서 issue 남깁니다.

**Comment by mrchypark** [comment]
안녕하세요 살펴보니 gitlab에 싱크가 동작하지 않네요. 우선

 remotes::install_github("mrchypark/multilinguer") 
 
 으로 설치하면 동작하실 겁니다. 
 
 위 코드로 설치하고도 문제가 생기면 알려주세요. 감사합니다.

**Comment by Joyeoh** [comment]
네 안녕하세요. 참고로 환경은 R studio 환경이고 알려주신 코드로 실행하니   install_jdk()를 했을 때
Error in zip::unzip(...) : 
  zip error: `Cannot open zip file `/tmp/RtmphsxnWr/crt.tar.gz` for reading` in file `zip.c:140`  
라는 오류가 다시 뜹니다 .  감사합니다.

**Comment by mrchypark** [comment]
안녕하세요. 코드 실행과 메세지 모두 공유해주실 수 있으신가요?

설치부분만 해주시면 좋을 것 같습니다.

아마 설치가 제대로 되지 않은 거 같아서요.

packageVersion("multilinguer") 도 보여주시면 좋을 것 같습니다.

**Comment by Joyeoh** [comment]
확인해보는 과정에서 다시 해보니 원인은 모르겠지만 문제가 해결되었습니다.
답변 감사합니다.

**Comment by mrchypark** [comment]
안녕하세요. 과거버전이 유지되었길래 확인 부탁드렸습니다.

아마 그 사이에 최신 버전으로 바뀌고 동작한 것 같습니다.

잘 수행되었다니 다행이네요. 감사합니다.

**Comment by mrchypark** [comment]
@all-contributors please add @HeoJongWon for bug
