### ISSUE TITLE
M1 mac install_jdk() 오류 

### ISSUE THREAD

**Issue by SeongIkKim** [mrchypark/multilinguer#39]
안녕하세요, 먼저 유용한 프로젝트 만들어주셔서 감사드립니다.

최근에 M1 mac을 사용하는 지인이 이 소스를 사용하다가 `install_jdk()` 혹은 `install_java()`에서 `rJava`가 제대로 설치되지 않는 이슈가 있었습니다. 타인의 컴퓨터라 자세한 에러메시지는 기억나지 않으나, jdk가 제대로 작동하지 않아 `rJava`를 설치할 수 없는 문제였습니다.

소스를 살펴보니 [해당 라인](https://github.com/mrchypark/multilinguer/blob/25b6b3bb2deb7e501da7aeb3d977325d6bb54e78/R/download_corretto.R#L28)에서 corretto 11을 받아 설치하는 듯한데, m1 native support가 아직 되지 않는 버전입니다.

관련 PR
- https://github.com/corretto/corretto-11/issues/165
- https://github.com/corretto/corretto-8/issues/340

corretto 11 개발 로드맵에는 있으니 남겨두시면 언젠가 해결은 될 지 모르나, 일단 코드상에는 arm64가 아닌 x86 체제만 고려하고 있는걸로 보여서 이슈남깁니다. 제가 R을 공부한 적이 없어 PR을 올리기 어려운 점 양해부탁드립니다. 만약 m1 지원을 고려하신다면 이용자의 아키텍쳐를 확인 후 arm64일시 Azul쪽 zulu-jdk를 사용하도록 분기처리하는 게 좋지 않을까 합니다.

일단은 이 라이브러리를 사용하지 않고 zulu-jdk 11을 직접 설치하여 rJava는 정상적으로 설치하였으며, 혹시 같은문제를 겪으시는 m1 mac사용자들은 아래의 링크를 참고하시면 좋을 것 같습니다.
- https://parinote.tistory.com/38
- https://github.com/konlpy/konlpy/issues/353
- https://llighter.github.io/install-java-on-mac/

**Comment by mrchypark** [comment]
@SeongIkKim 안녕하세요 이슈 남겨주셔서 대단히 감사합니다.

mac m1을 신경써야 할 거라고는 생각지 못했는데, 알려주신 덕분에 문제의식을 가질 수 있게 되었습니다.
본 프로젝트는 자바 설치에 대한 경로 설정등의 지식이 없거나 하여 블로그 등도 따라하기 어려운 분들을 위해 제작하였습니다.
맥은 상대적으로 해당되는 사용자가 적을 것이라 생각하고 있었는데, 옆에서 보신 모양입니다.

공유해주신 이슈처럼 mac arm64는 zulu를 제공하는 것으로 제가 작업할 수 있을 것 같습니다.

혹시 다음에 기회가 되신다면, 지인분께 R 콘솔에서 Sys.info() 명령을 수행하고 출력 전체를 공유해주실 수 있으실까요?
제가 주변으로도 찾아보겠습니다만 혹시 가능하시다면 부탁드리겠습니다.

다시 한 번 이슈 생성해주셔서 감사합니다.

**Comment by SeongIkKim** [comment]
<img width="768" alt="sysinfo" src="https://user-images.githubusercontent.com/26772420/145059707-fecf7ad3-58be-4572-924f-06183fd8524d.png">

지인에게 부탁하여 Sys.info() 반환값 이미지를 첨부합니다.
이용자 개인이 식별될 수 있는 정보는 제거하였습니다. 고생많으십니다.

**Comment by mrchypark** [comment]
@SeongIkKim 오 바로 알려주셔서 감사합니다. 개인정보 부분도 처리해주셔서 정말 감사드립니다. :)

적용 개발할 때 많은 도움이 되었습니다.

**Comment by mrchypark** [comment]
@all-contributors please add @SeongIkKim for platform

**Comment by mrchypark** [comment]
https://docs.microsoft.com/ko-kr/java/openjdk/download

ms jdk는 17만 m1을 지원하는걸 확인.
zulu만 대안으로 보임

**Comment by mrchypark** [comment]
Liberica JDK 도 제공함
