### ISSUE TITLE
R Java Konlp 패키지 오류 문의 올립니다. R 4.1.0 재설치 후 오류 입니다. ㅠㅠ 도움 부탁 드립니다.

### ISSUE THREAD

**Issue by BaeBJH** [mrchypark/multilinguer#47]
R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("remotes")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/remotes_2.4.2.zip'
Content type 'application/zip' length 399642 bytes (390 KB)
downloaded 390 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\bjh\AppData\Local\Temp\RtmpAjGGez\downloaded_packages
> remotes::install_github("anthonynorth/rscodeio")
Skipping install of 'rscodeio' from a github remote, the SHA1 (88a1a373) has not changed since last install.
  Use `force = TRUE` to force installation
> rscodeio::install_theme()
Warning message:
In .rs.removeTheme(name, .rs.getThemes()) :
  Removing the active theme - setting the current theme to Tomorrow Night
> Sys.getenv("JAVA_HOME")
[1] "C:/java/jdk-11"
> install.packages("rJava")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/rJava_1.0-6.zip'
Content type 'application/zip' length 1513770 bytes (1.4 MB)
downloaded 1.4 MB

package ‘rJava’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\bjh\AppData\Local\Temp\RtmpAjGGez\downloaded_packages
> source("https://install-github.me/talgalili/installr")
The install-github.me service is deprecated, please stop using it.
Skipping install of 'installr' from a github remote, the SHA1 (abd64389) has not changed since last install.
  Use `force = TRUE` to force installation
> installr::install.java()
trying URL 'https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_windows-x64_bin.zip'
Content type 'application/zip' length 187396683 bytes (178.7 MB)
downloaded 178.7 MB

> library(rJava)
Warning message:
패키지 ‘rJava’는 R 버전 4.1.2에서 작성되었습니다 
> install.packages('KoNLP')
Warning in install.packages :
  package ‘KoNLP’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> source("https://install-github.me/talgalili/installr")
The install-github.me service is deprecated, please stop using it.
Skipping install of 'installr' from a github remote, the SHA1 (abd64389) has not changed since last install.
  Use `force = TRUE` to force installation
> installr::install.java()
trying URL 'https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_windows-x64_bin.zip'
Content type 'application/zip' length 187396683 bytes (178.7 MB)
downloaded 178.7 MB

Error in unzip(zipfile = filename, exdir = path) : 
  cannot open file 'C:/java/jdk-11/bin/server/jvm.dll': Permission denied
> library(KoNLP)
Error in library(KoNLP) : ‘KoNLP’이라고 불리는 패키지가 없습니다

**Comment by mrchypark** [comment]
@BaeBJH 지금 오류는 이 패키지를 사용하신게 아니군요.

제가 도움드리기 어려운 범위이지 싶습니다.
rJava까지 잘 설치되고 로드 되는 것으로 보아 자바 설치 자체는 잘 끝난 것 같습니다.

현재 KoNLP가 CRAN에 없어 `install.packages('KoNLP')` 이 함수로 설치를 진행할 수 없습니다.
이 단계가 진행되지 않은 것 같은데요. 개발 버전으로 설치해보시기 바랍니다.

감사합니다.

**Comment by BaeBJH** [comment]
감사합니다.
제가 개발 버전 설치를 몰라서 문의올립니다.
개발 버전으로 설치하는 방법 관련 웹이나 코드 나온 것 알려주실 수 있을까요? ㅠㅠ
번거롭게해 송구합니다. ㅠ

2021년 12월 13일 (월) 오후 1:08, ChanYub Park ***@***.***>님이 작성:

**Comment by mrchypark** [comment]
https://mrchypark.github.io/post/KoNLP-%EC%84%A4%EC%B9%98-%EB%B0%A9%EB%B2%95/

위 링크를 참고하였습니다.

```
install.packages("KoNLP", 
    repos = c("https://forkonlp.r-universe.dev",
              "https://cloud.r-project.org"),
    INSTALL_opts = c("--no-multiarch")
  )
```

**Comment by BaeBJH** [comment]
감사합니다. ㅠㅠ
처음 페북 문의에서 슬통 R 설치대로 했습니다만,
만일 R 4.0 재설치가 필요한건지요? 다시 세팅이 필요할 수 있으니 관련 내용도 안내 부탁드려도 되겠습니까?
부탁과 요구가 너무 많아 면구합니다. ㅠㅠ

2021년 12월 13일 (월) 오후 1:21, ChanYub Park ***@***.***>님이 작성:

**Comment by mrchypark** [comment]
버전체계에 대해 간단히 설명드리면 메이저.마이너.패치의 형태를 띕니다.
R은 메이저, 마이너 버전 변경시 패키지 설치 경로를 따로 관리하도록 동작합니다.
그렇기 때문에 4.0 때 패키지를 설치 하셨더라도, 4.1 을 사용하시려면 새롭게 패키지들을 설치하셔야 합니다.

그래서 다시 설치하는 과정이 필요한 것 뿐이니 R은 최신 버전을 유지하시길 권장드립니다.

**Comment by BaeBJH** [comment]
바쁘신데 자꾸 번거롭게 해 드려 면구합니다.
안내된 링크대로 했습니다만, 이렇게 Konlp 패키지 오류가 나는 듯 합니다. R 4.1.2 최신 버전 재설치 해보면 되겠습니까?


R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> install.packages("rJava")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/rJava_1.0-6.zip
'
Content type 'application/zip' length 1513770 bytes (1.4 MB)
downloaded 1.4 MB

package ‘rJava’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\bjh\AppData\Local\Temp\RtmpgTyPce\downloaded_packages
> rJava::.jinit()
> rJava::.jinit()
[1] 0
> install.packages("multilinguer")
Warning in install.packages :
  package ‘multilinguer’ is not available for this version of R

A version of this package for your version of R might be available
elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> install.packages("multilinguer")
Warning in install.packages :
  package ‘multilinguer’ is not available for this version of R

A version of this package for your version of R might be available
elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
> multilinguer::install_jdk()
trying URL '
https://corretto.aws/downloads/latest/amazon-corretto-11-x64-windows-jdk.zip
'
Content type 'binary/octet-stream' length 186995510 bytes (178.3 MB)
downloaded 178.3 MB

JDK will located at C:/Users/bjh/.corretto
ENV will set
JAVA_HOME= C:/Users/bjh/.corretto/jdk11.0.13_8
PATH=
%JAVA_HOME%\bin;C:\R\R-4.1.0\bin\x64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
Files (x86)\NVIDIA
Corporation\PhysX\Common;C:\R\rtools40\\usr\bin\;C:\R\rtools40\usr\bin\;C:/Users/bjh/.corretto/jdk11.0.13_8\bin;C:\Users\bjh\AppData\Local\Microsoft\WindowsApps;C:\R\RStudio\bin\rpostback;C:\R\RStudio\bin\postback
Warning messages:
1: In dir.create(path) :
  'C:\Users\bjh\AppData\Local\Temp\RtmpgTyPce' already exists
2: In dir.create(path) : 'C:\Users\bjh' already exists
3: In dir.create(path) : 'C:\Users\bjh' already exists

Restarting R session...

>
install.packages('rJava');library(rJava);.jinit();rstudioapi::restartSession()
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/rJava_1.0-6.zip
'
Content type 'application/zip' length 1513770 bytes (1.4 MB)
downloaded 1.4 MB

package ‘rJava’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\bjh\AppData\Local\Temp\RtmpquqkEs\downloaded_packages
Warning message:
패키지 ‘rJava’는 R 버전 4.1.2에서 작성되었습니다

Restarting R session...

> rJava::.jinit()
Warning message:
패키지 ‘rJava’는 R 버전 4.1.2에서 작성되었습니다
> rJava::.jinit()
[1] 0
> install.packages("KoNLP",
+                  repos = c("https://forkonlp.r-universe.dev",
+                            "https://cloud.r-project.org"),
+                  INSTALL_opts = c("--no-multiarch")
+ )
trying URL '
https://forkonlp.r-universe.dev/bin/windows/contrib/4.1/KoNLP_0.80.2.zip'
Content type 'application/zip' length 5905973 bytes (5.6 MB)
downloaded 5.6 MB

package ‘KoNLP’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\bjh\AppData\Local\Temp\Rtmp6JLp7W\downloaded_packages
> library("KoNLP")
Error: package or namespace load failed for ‘KoNLP’:
 .onLoad가 loadNamespace()에서 'KoNLP'때문에 실패했습니다:
  호출: fun(libname, pkgname)
  에러: You cann't parse resource files based on UTF-8 on rJava. Please
reload KoNLP first than any other packages connected with rJava.
In addition: Warning message:
패키지 ‘KoNLP’는 R 버전 4.1.2에서 작성되었습니다



2021년 12월 13일 (월) 오후 1:42, ChanYub Park ***@***.***>님이 작성:

**Comment by BaeBJH** [comment]
제일 아래 환경변수 관련 주의를 읽었습니다. R 설치하며 Rtools 환경변수 변경하였습니다. ㅠㅠ

2021년 12월 13일 (월) 오후 1:57, 배정호 ***@***.***>님이 작성:

**Comment by mrchypark** [comment]
음... 자바 설치는 문제없이 되었기 때문에 다시 하실 필요가 없어 보입니다.

KoNLP 설치가 잘 안되는거 같은데, 이건 저도 처음보는 에러네요. 
한번 Rstudio를 완전히 끄고 다시 KoNLP만 설치해서 로드해보시겠어요?

**Comment by BaeBJH** [comment]
감사합니다 ㅠㅠ

2021년 12월 13일 (월) 오후 2:01, ChanYub Park ***@***.***>님이 작성:

**Comment by BaeBJH** [comment]
감사합니다. 덕분에 가장 큰 산을 넘었습니다. 조마조마 하며 재부팅 하니 됩니다. ㅠㅠ
그동안 Rtools 와 Konlp 설치오류로 3.6 대 버전만 사용했습니다. '최대한 쉽게 쓴...' 웹페이지 매번 참고했었습니다.
이번에 버전 업을 하게 되어 새로운 세계가 열렸습니다.
다시한번 감사 또 감사 드립니다. 큰 도움에 보답 드릴 길이 없어,  연구에 관심이 있으신 것 같아 졸저 참고로 보내드립니다(출판사와
저작권 문제로 유출되면 안되는 것이오니 참고용으로만 부탁드립니다.)
매번 큰 도움 주심에 다시한번 감사 드립니다.

https://drive.google.com/file/d/1Mo8UKnoHulVaG_Gg4cRAC98avyksMLxC/view?usp=sharing

2021년 12월 13일 (월) 오후 4:22, 배정호 ***@***.***>님이 작성:
