### ISSUE TITLE
multilinguer 설치 문의

### ISSUE THREAD

**Issue by GraceGEKim** [mrchypark/multilinguer#48]
안녕하세요.

KoNLP 설치 이슈 페이스북 포스트 올려주셔서 감사합니다. 올려주신 포스트를 따라 설치하고 있는데 multilinguer 패키지를 설치하려면 계속해서 같은 오류 메세지가 떠서 질문드립니다. 

java, rJava 설치 install.packages("multilinguer") 부분에서 다음과 같은 메세지가 뜨면서 설치가 되지 않습니다.  window 사용하고 있으며, R은 4.1.2 버전 사용중입니다. 

> install.packages("multilinguer")
Installing package into ‘C:/Users/Goni/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages : package ‘multilinguer’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

감사합니다.

**Comment by mrchypark** [comment]
@GraceGEKim 안녕하세요. 현재 패키지 설계와 CRAN 간 정책 이슈가 있어서 CRAN에서 내려가 있는 상태입니다.
```
remotes::install_github("mrchypark/multilinguer")
```
로 설치하시면 동작할겁니다.
감사합니다.
