### ISSUE TITLE
install_keras Function Error

### ISSUE THREAD

**Issue by bongho** [mrchypark/multilinguer#7]
install.packages("keras")
library(keras)
install_keras()

위 순서대로 실행시, 아래와 같이 오류가 발생합니다.

**Error in install_keras() : could not find function "install_keras"**

**Comment by mrchypark** [comment]
이건 이상하네요 ㅠ 확인해보겠습니다!

**Comment by bongho** [comment]
multilinguer 패키지 재설치 이후 정상 작동합니다. ;)

감사합니다.
