### ISSUE TITLE
has_conda() function 실행시 에러

### ISSUE THREAD

**Issue by bongho** [mrchypark/multilinguer#8]
> library(multilinguer)
> has_conda()
Error in grepl("Windows", class(os)) : object 'os' not found

**Comment by mrchypark** [comment]
빠르게 테스트해주셔서 감사합니다 ㅠㅠ

수정했습니다. 확인해주시면 감사하겠습니다!

**Comment by bongho** [comment]
지우고 다시 설치해봤더니, 에러 발생하지 않습니다! :) 

감사합니다.

**Comment by mrchypark** [comment]
@all-contributors please add @bongho for test
